// Generated by CoffeeScript 1.9.3
(function() {
  app.factory('NotesFactory', function() {
    return {
      remove: function(note) {
        localStorage.removeItem("note" + note.id);
        return this.getAll();
      },
      removeAll: function() {
        return localStorage.clear();
      },
      put: function(note) {
        localStorage.setItem('note' + note.id, JSON.stringify(note));
        return this.getAll();
      },
      get: function(index) {
        return JSON.parse(localStorage.getItem("note" + index));
      },
      getAll: function() {
        var key, note, notes;
        notes = [];
        for (key in localStorage) {
          note = localStorage[key];
          if (key.indexOf('note' > -1)) {
            notes.push(JSON.parse(note));
          }
        }
        return notes;
      }
    };
  });

}).call(this);
