// Generated by CoffeeScript 1.9.3
(function() {
  app.directive('noteNavigation', function() {
    return {
      restrict: 'E',
      scope: {
        note: '='
      },
      require: '^notepad',
      templateUrl: 'templates/noteNavigation.html',
      link: function(scope, elem, attrs, notepadCtrl) {
        return scope.remove = function() {
          return notepadCtrl.remove(scope.note);
        };
      }
    };
  });

}).call(this);
