// Generated by CoffeeScript 1.9.3
(function() {
  app.directive('notepad', function(NotesFactory) {
    return {
      restrict: 'AE',
      scope: {},
      templateUrl: 'templates/notepad.html',
      controller: function($scope) {
        this.remove = function(note) {
          return $scope.notes = NotesFactory.remove(note);
        };
        return false;
      },
      link: function(scope, elem, attrs) {
        var editor;
        scope.openEditor = function(index) {
          scope.editMode = true;
          if (index !== void 0) {
            scope.noteText = NotesFactory.get(index).content;
            return scope.index = index;
          } else {
            return scope.noteText = void 0;
          }
        };
        scope.save = function() {
          var note;
          if (scope.noteText !== "" && scope.noteText !== void 0) {
            note = {};
            note.title = scope.noteText.length > 10 ? scope.noteText.substring(0, 10) + '. . .' : scope.noteText;
            note.content = scope.noteText;
            note.id = scope.index !== -1 ? scope.index : localStorage.length;
            scope.notes = NotesFactory.put(note);
          }
          return scope.restore();
        };
        scope.restore = function() {
          scope.editMode = false;
          scope.index = -1;
          return scope.noteText = "";
        };
        editor = elem.find('#editor');
        scope.restore();
        scope.notes = NotesFactory.getAll();
        return editor.bind('keyup keydown', function() {
          return scope.noteText = editor.text().trim();
        });
      }
    };
  });

}).call(this);
